### ISSUE TITLE
Тестовые панорамы Pano2VR

### ISSUE THREAD

**Issue by dobatovkin** [dobatovkin/geo-bsu-map#3]

**Comment by Arhemon** [comment]
![2023-04-03 00 18 48](https://user-images.githubusercontent.com/97899597/229379528-47548508-9ba5-4675-a73d-fe0fa1a0d1ec.jpg)
![2023-04-03 00 18 42](https://user-images.githubusercontent.com/97899597/229379529-ac676ca2-8d38-46cc-9b40-6a8b9913d269.jpg)
![photo_2023-04-02_14-34-50_stitch](https://user-images.githubusercontent.com/97899597/229379531-9ef6a2ad-9871-4836-af4b-6ea1dcbe654f.jpg)
